### ISSUE TITLE
I need to uninstall and install the ScanX app whenever I restart my pc

### ISSUE THREAD

**Issue by pwong2** [balbarak/scanx#3]
I've noticed that I need to uninstall and install the ScanX app whenever I restart my pc/laptop. Any help on that?

**Comment by pwong2** [comment]
@balbarak @looksharp please help

**Comment by pwong2** [comment]
@balbarak @looksharp

**Comment by balbarak** [comment]
Hello,

Kindly check the service my be it is stopped for some reason or it is not auto start.

The service name is Scanx

**Comment by pwong2** [comment]
@balbarak @looksharp You are correct, I found out that the ScanX service is stopped. I set it to Automatically start after reboot, however, it is not starting automatically. Do you know why? I'm kinda stuck of this.. thanks

**Comment by pwong2** [comment]
@balbarak @looksharp

**Comment by pwong2** [comment]
https://support.microsoft.com/en-us/help/839803/the-windows-trace-session-manager-service-does-not-start-and-event-id solved the issue
